base:
  config:
    oauth:
      hostname: 124.71.179.190
      port: 9002
    nacos:
      hostname: 127.0.0.1
      port: 8848
    db:
      hostname: 124.71.179.190
      port: 3307
    redis:
      hostname: 124.71.179.190
      port: 6379
      password: youche123
#    mongodb:
#      hostname: 192.168.188.36
#      port: 27017
spring:
  application:
    name: business-capital
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
        group: YOUCHE_GROUP
#        ip: 192.168.20.104
    inetutils:
      preferred-networks: 192.168.20
  redis:
    # Redis数据库索引（默认为0)
    database: 0
    # Redis服务器地址
    host: ${base.config.redis.hostname}
    # Redis服务器连接端口
    port: ${base.config.redis.port}
    # Redis服务器连接密码（默认为空）
    password: ${base.config.redis.password}
server:
  port: 9004

logging:
  level:
    com.youming.youche.capital.business.controller: debug
  #将日志输出到文件
  config: classpath:dev-log.xml



dubbo:
  scan:
    base-packages: com.youming.youche.capital.business.controller
  protocol:
    name: dubbo
    port: -1
#    host: 192.168.20.104
#    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}
    group: YOUCHE_GROUP
#    register: true
#    subscribe: true
#  provider:
#    loadbalance: roundrobin
  metadata-report:
    address: nacos://${base.config.nacos.hostname}:${base.config.nacos.port}
  consumer:
    timeout: 50000
    retries: 0

