base:
  config:
    oauth:
      hostname: 124.71.179.190
      port: 9002
    nacos:
      hostname: 127.0.0.1
      port: 8848
    redis:
      hostname: 124.71.179.190
      port: 6379
      password: youche123
#    mongodb:
#      hostname: 192.168.188.36
#      port: 27017
spring:
  application:
    name: business-table
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}
        group: YOUCHE_GROUP
  redis:
    # Redis数据库索引（默认为0)
    database: 0
    # Redis服务器地址
    host: ${base.config.redis.hostname}
    # Redis服务器连接端口
    port: ${base.config.redis.port}
    # Redis服务器连接密码（默认为空）
    password: ${base.config.redis.password}
    # 我们使用 Lettuce 客户端，比 Jedis 更高效
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
    timeout: 50000

server:
  port: 9010

logging:
  level:
    com.youming.youche.table.business.controller: debug
  #将日志输出到文件
  config: classpath:dev-log.xml



dubbo:
  scan:
    base-packages: com.youming.youche.table.business.controller
  protocol:
    name: dubbo
    port: -1
#    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}
    port: ${base.config.nacos.port}
    group: YOUCHE_GROUP
  metadata-report:
    address: nacos://${base.config.nacos.hostname}:${base.config.nacos.port}
  provider:
    loadbalance: roundrobin
    timeout: 250000
  consumer:
    timeout: 5000000
    retries: 0

