base:
  config:
    nacos:
      hostname: 10.17.80.14
      port: 8848
    db:
      hostname: 10.17.80.16
#      hostname: 192.168.88.111
      port: 3307
    redis:
      hostname: 10.17.80.15
      port: 6379
#    mongodb:
#      hostname: 192.168.188.36
#      port: 27017
spring:
  application:
    name: provider-system
  main:
    allow-bean-definition-overriding: true
  cloud:
    alibaba:
      seata:
        tx-service-group: tx_group
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.db.hostname}:${base.config.db.port}/youche?serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false&nullNamePatternMatchesAll=true&zeroDateTimeBehavior=CONVERT_TO_NULL&tinyInt1isBit=false&autoReconnect=true&useSSL=false&pinGlobalTxToPhysicalConnection=true
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    # Redis数据库索引（默认为0)
    database: 0
    # Redis服务器地址
    host: ${base.config.redis.hostname}
    # Redis服务器连接端口
    port: ${base.config.redis.port}
    # Redis服务器连接密码（默认为空）
    password: youche123
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
    timeout: 5000
  jackson:
    # 设置属性命名策略,对应jackson下PropertyNamingStrategy中的常量值，SNAKE_CASE-返回的json驼峰式转下划线，json body下划线传到后端自动转驼峰式
    property-naming-strategy: SNAKE_CASE
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd HH:mm:ss
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8
    # 常用，全局设置pojo或被@JsonInclude注解的属性的序列化方式
    default-property-inclusion: NON_NULL #不为空的属性才会序列化,具体属性可看JsonInclude.Include
    # 常规默认,枚举类SerializationFeature中的枚举属性为key，值为boolean设置jackson序列化特性,具体key请看SerializationFeature源码
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true # 返回的java.util.date转换成timestamp
      FAIL_ON_EMPTY_BEANS: true # 对象为空时是否报错，默认true
    # 枚举类DeserializationFeature中的枚举属性为key，值为boolean设置jackson反序列化特性,具体key请看DeserializationFeature源码
    deserialization:
      # 常用,json中含pojo不存在属性时是否失败报错,默认true
      FAIL_ON_UNKNOWN_PROPERTIES: false
    # 枚举类MapperFeature中的枚举属性为key，值为boolean设置jackson ObjectMapper特性
    # ObjectMapper在jackson中负责json的读写、json与pojo的互转、json tree的互转,具体特性请看MapperFeature,常规默认即可
    mapper:
      # 使用getter取代setter探测属性，如类中含getName()但不包含name属性与setName()，传输的vo json格式模板中依旧含name属性
      USE_GETTERS_AS_SETTERS: true #默认false
    # 枚举类JsonParser.Feature枚举类中的枚举属性为key，值为boolean设置jackson JsonParser特性
    # JsonParser在jackson中负责json内容的读取,具体特性请看JsonParser.Feature，一般无需设置默认即可
    parser:
      ALLOW_SINGLE_QUOTES: true # 是否允许出现单引号,默认false
    # 枚举类JsonGenerator.Feature枚举类中的枚举属性为key，值为boolean设置jackson JsonGenerator特性，一般无需设置默认即可
    # JsonGenerator在jackson中负责编写json内容,具体特性请看JsonGenerator.Feature


logging:
  level:
    com.youming.youche.system.mapper: info
  #将日志输出到文件
  config: classpath:provider-system-log.xml


dubbo:
  scan:
    base-packages: com.youming.youche.system.provider.service
  protocol:
    name: dubbo
    port: -1
#    host: 192.168.20.103
  #    host: ${base.config.nacos.hostname}
  registry:
    address: nacos://${base.config.nacos.hostname}:${base.config.nacos.port}
    group: YOUCHE_GROUP
  provider:
    filter: -exception,dubboExceptionFilter
    timeout: 50000
    retries: 0
  consumer:
    check: false
    timeout: 50000
    retries: 0






seata:
  config:
    type: nacos
    nacos:
      server-addr: ${base.config.nacos.hostname}:8848
      group: "SEATA_GROUP"
      namespace: "c86e0f15-2904-4c2a-a7a2-f9c3a58b6973"
      username: "nacos"
      password: "nacos"
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${base.config.nacos.hostname}:8848
      group: "SEATA_GROUP"
      namespace: "c86e0f15-2904-4c2a-a7a2-f9c3a58b6973"
      username: "nacos"
      password: "nacos"

